$(document).ready(function() {
    $('.clickable').click(function() {
        $('.design-description').slideToggle();
        $('.design-icon').slideToggle();
    });
    $('.clickable1').click(function() {
        $('.development-description').slideToggle();
        $('.development-icon').slideToggle();
    });
    $('.clickable2').click(function () {
        $('.product-description').slideToggle();
        $('.product-icon').slideToggle();
    });
});
$(document).ready(function(){
    $("#portfolio1").mouseover(function(){
      $("#overlay1").show();
    }).mouseout(function(){
      $("#overlay1").hide();
    });
  });
  $(document).ready(function(){
    $("#portfolio2").mouseover(function(){
      $("#overlay2").show();
    }).mouseout(function(){
      $("#overlay2").hide();
    });
  });
  $(document).ready(function(){
    $("#portfolio3").mouseover(function(){
      $("#overlay3").show();
    }).mouseout(function(){
      $("#overlay3").hide();
    });
  });
  $(document).ready(function(){
    $("#portfolio4").mouseover(function(){
      $("#overlay4").show();
    }).mouseout(function(){
      $("#overlay4").hide();
    });
  });
  $(document).ready(function(){
    $("#portfolio5").mouseover(function(){
      $("#overlay5").show();
    }).mouseout(function(){
      $("#overlay5").hide();
    });
    $("#portfolio6").mouseover(function(){
      $("#overlay6").show();
    }).mouseout(function(){
      $("#overlay6").hide();
    });
    $("#portfolio7").mouseover(function(){
      $("#overlay7").show();
    }).mouseout(function(){
      $("#overlay7").hide();
    });
    $("#portfolio8").mouseover(function(){
      $("#overlay8").show();
    }).mouseout(function(){
      $("#overlay8").hide();
    });
  });
  $(document).ready(function(){
    $("#submit").click(function(){        
        $("#myForm").submit();
    });
});